TaskManager/common/urls.py
from django.urls import path

from TaskManager.common.views import NewsCreateView, comment_article, NewsDetailView, news_delete, NewsEditView

urlpatterns = [
    path('news-create/', NewsCreateView.as_view(), name='news create'),
    path('<int:pk>/article-comment/', comment_article, name='comment article'),
    path('<int:pk>/article-view/', NewsDetailView.as_view(), name='details article'),
    path('<int:pk>/article-edit/', NewsEditView.as_view(), name='edit article'),
    path('<int:pk>/article-delete/', news_delete, name='delete article'),
]

TaskManager/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from TaskManager import settings
from TaskManager.common.views import HomePage
from TaskManager.core.exception_handler import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home page'),
    path('accounts/', include('TaskManager.accounts.urls')),
    path('tasks/', include('TaskManager.tasks.urls')),
    path('vacations/', include('TaskManager.vacations.urls')),
    path('common/', include('TaskManager.common.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

TaskManager/common/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models

from TaskManager.tasks.models import Task

UserModel = get_user_model()


class ShortNewsArticle(models.Model):
    MAX_TEXT_TITLE_LEN = 40
    MAX_TEXT_LEN = 300
    NAME_MIN_LEN = 10
    ARTICLE_MIN_LEN = 10
    ARTICLE_MAX_LEN = 50

    news_Title = models.CharField(
        max_length=MAX_TEXT_TITLE_LEN,
        null=False,
        blank=False,
        validators=[MinLengthValidator(NAME_MIN_LEN, f'Name should be min {NAME_MIN_LEN} chars'), ]
    )
    news_article = models.CharField(
        max_length=MAX_TEXT_LEN,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(ARTICLE_MIN_LEN, f'Name should be min {ARTICLE_MIN_LEN} chars'),
            MaxLengthValidator(ARTICLE_MAX_LEN, f'Article should be maz {ARTICLE_MAX_LEN} chars'),
        ]
    )

    date_and_time = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT
    )

    def __str__(self):
        return f'{self.news_Title} by {self.user}'


# Future extensibility with task comments
#
# class TaskComment(models.Model):
#     MAX_TEXT_LEN = 255
#
#     task_comment = models.CharField(
#         max_length=MAX_TEXT_LEN,
#         null=False,
#         blank=True,
#     )
#
#     commented_section = models.ForeignKey(
#         Task,
#         on_delete=models.RESTRICT,
#         null=False,
#         blank=True,
#     )
#
#     date_and_time = models.DateTimeField(
#         auto_now_add=True,
#         null=False,
#         blank=False,
#     )
#     comment_user = models.ForeignKey(
#         UserModel,
#         on_delete=models.RESTRICT,
#     )
#

class NewsComment(models.Model):
    MAX_TEXT_LEN = 255
    COMMENT_MIN_LEN = 2

    news_comment = models.CharField(
        max_length=MAX_TEXT_LEN,
        # validators=[MinLengthValidator(COMMENT_MIN_LEN, f'Comment should have at least{COMMENT_MIN_LEN} char.'), ],
        null=False,
        blank=False,
    )

    commented_section = models.ForeignKey(
        ShortNewsArticle,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )

    date_and_time = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
    )

    comment_user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

TaskManager/common/forms.py
from django import forms

from TaskManager.common.models import NewsComment, ShortNewsArticle


class NewsCommentForm(forms.ModelForm):
    class Meta:
        model = NewsComment
        fields = ('news_comment',)


# Future extensibility with task comments
# class TaskCommentForm(forms.ModelForm):
#     class Meta:
#         model = TaskComment
#         fields = '__all__'
#

class NewsCreateForm(forms.ModelForm):
    class Meta:
        model = ShortNewsArticle
        exclude = ('user', 'date_and_time_of_article',)
        widgets = {
            'news_Title': forms.TextInput(attrs={'placeholder': 'Title here...'}),
            'news_article': forms.Textarea(
                attrs={
                    'cols': 20,
                    'rows': 5,
                    'placeholder': '  Write here....',
                }
            ),
        }


class EditNewsForm(forms.ModelForm):
    class Meta:
        model = ShortNewsArticle
        exclude = ('user', 'date_and_time_of_article',)
        widgets = {
            'news_Title': forms.TextInput(attrs={'placeholder': 'Title here...'}),
            'news_article': forms.Textarea(
                attrs={
                    'cols': 20,
                    'rows': 5,
                    'placeholder': '  Write here....',
                }
            ),
        }

TaskManager/common/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import mixins as auth_mixins, get_user_model
# from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views import generic as views
from TaskManager.common.forms import NewsCommentForm, NewsCreateForm
from TaskManager.common.models import ShortNewsArticle

UserModel = get_user_model()


class HomePage(views.ListView):

    # model = UserModel
    model = ShortNewsArticle
    template_name = 'index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        news = ShortNewsArticle.objects.all().order_by('-pk')
        context['news'] = news
        context['comment_form'] = NewsCommentForm()
        return context


class NewsCreateView(auth_mixins.LoginRequiredMixin, views.CreateView):
    template_name = 'base/base-create-view.html'
    form_class = NewsCreateForm

    success_url = reverse_lazy('home page')

    def form_valid(self, form):
        news = form.save(commit=False)
        # 2:
        # We add info about the current user News.user field
        news.user = self.request.user
        # 3:
        # Now we can populate autogenerated id field
        news.save()
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Create News'
        context['form__button_title'] = 'CREATE'
        if not self.request.user.is_general_manager:
            raise PermissionDenied()
        return context


@login_required
def comment_article(request, pk):
    # We can use default article get:
    # article = ShortNewsArticle.objects.filter(pk=pk).get()
    # or we can use django shortcuts : get_object_or_404
    article = get_object_or_404(ShortNewsArticle, pk=pk)

    form = NewsCommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)  # Does not persist to DB
        comment.commented_section = article
        comment.comment_user = request.user
        comment.save()

    return redirect('home page')


# def home_page(request):
#     news = ShortNewsArticle.objects.all()
#     users = UserModel.objects.all()
#     if request.method == "POST":
#         comment_form = NewsCommentForm(request.POST)
#         if comment_form.is_valid():
#             comment = comment_form.save(commit=False)
#             comment.comment_user = request.user
#             comment_form.save()
#             return redirect('home page')
#     else:
#         comment_form = NewsCommentForm()
#
#     context = {
#         'news': news,
#         'object_list': users,
#         'comment_form': comment_form,
#     }
#     return render(request, template_name='index.html', context=context)


class NewsDetailView(auth_mixins.LoginRequiredMixin, views.DetailView):
    template_name = 'common/news-details.html'
    model = ShortNewsArticle


def news_delete(request, pk):
    # We can use default article get:
    # article = ShortNewsArticle.objects.filter(pk=pk).get()
    # or we can use django shortcuts : get_object_or_404,
    # or we can use custom exception handler
    try:
        vacation = ShortNewsArticle.objects.filter(pk=pk).get()
    except ObjectDoesNotExist as ex:
        raise Http404
    vacation.delete()
    return redirect('home page')


class NewsEditView(auth_mixins.LoginRequiredMixin, views.UpdateView):
    model = ShortNewsArticle
    template_name = 'base/base-edit-view.html'
    fields = ['news_Title', 'news_article', ]
    success_url = reverse_lazy('home page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Edit News'
        context['form__button_title'] = 'EDIT'
        if not self.request.user.is_general_manager:
            raise PermissionDenied()
        return context

templates/common/news-create.html
{% extends 'base/base.html' %}
{% load static %}
{% load placeholders %}
{% block content_page %}
    <section id="register-page" class="content auth">
        <form id="register" method="post">
            <div class="container">
                <div class="brand-logo"></div>
                <h1>Create News</h1>
                <form method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <input class="btn submit" type="submit" value="Save the article">
                </form>
            </div>
        </form>
    </section>
{% endblock %}

templates/common/news-details.html
{% extends 'base/base.html' %}
{% load static %}
{% block content_page %}
    <!-- profile details section -->
    <section id="car-details">
        <h1>Article </h1>
        <div class="info-section">
            <div class="car-header">
                <!-- user username -->
                <p class="description">Title: {{ object.news_Title }}</p>
                <!-- user email -->
                <p class="description">Atricle: {{ object.news_article }}</p>
                <!-- user age -->
                <p style="color:white">Comments:</p>
                {% for comment in object.newscomment_set.all %}
                    <div style="border-width:1px; border-style:solid; border-color:white; padding: 1em;">
                        <h4 style="color:white; text-align:left;max-width: 100%;">
                            {{ comment.comment_user.get_full_name }} commented:</h4>
                        <h5 style="color:white; text-align:left;"> {{ comment.news_comment }}</h5>
                        <h6 style="color:greenyellow; text-align:left;">{{ comment.date_and_time }}</h6>
                    </div>
                {% endfor %}

                {% if request.user.is_general_manager %}
                    <div class="buttons" style="text-align: center; padding-top:20px">
                        <a href="{% url 'edit article' pk=object.pk %}" class="edit-button">Edit</a>
                        <a href="{% url 'delete article' pk=object.pk %}" class="delete-button">Delete</a>
                    </div>
                {% endif %}


            </div>
        </div>
    </section>

{% endblock %}

templates/common/news-edit.html
{% extends 'base/base.html' %}
{% block content_page %}


    <!-- edit car form -->
    <section id="create-page" class="auth">
        <form id="create" method="post">
            <div class="container">

                <h1>Edit News</h1>
                {{ form }}
                {% csrf_token %}
                <input class="btn submit" type="submit" value="Save Changes">
            </div>
        </form>
    </section>

{% endblock %}